export const ADD_EVENT = 'ADD_EVENT'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const SELECTALL_EVENTS = 'SELECTALL_EVENTS'
export const DESELECTALL_EVENTS = 'DESELECTALL_EVENTS'
export const TOGGLE_EVENT = 'TOGGLE_EVENT'
export const FILTER_TEXT = 'FILTER_TEXT'

